const {addTrip, getTrip, getWeather, cancelTrip, acceptTrip, removeTrip} = require('../controllers/TripController')
const {verifyToken} = require("../middlewares/UserMiddleware")
const file = require('../middlewares/TripTicketUploadMiddleware')
const router = require('express').Router()
router.post("/addTrip",verifyToken,file.single('image'),addTrip)
router.get("/getTrip",verifyToken,getTrip)
router.get("/getWeather",verifyToken,getWeather)
router.get("/cancelTrip",verifyToken,cancelTrip)
router.post("/acceptTrip",verifyToken,acceptTrip)
router.post("/rejectTrip",verifyToken,removeTrip)
module.exports = router